services:
  nvidia-sdkmanager:
    image: ${SDKMANAGER_IMAGE:-sdkmanager:latest}
    privileged: true
    stdin_open: true
    tty: true
    network_mode: ${SDKM_DOCKER_NETWORK:-host}
    command:
      - --cli
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev:/dev
      - ${SDKM_MEDIA_DIR}:/media/nvidia:slave
      - ${SDKM_DOWNLOADS_DIR}:/home/nvidia/Downloads/nvidia/sdkm_downloads
      - ${SDKM_TARGET_IMAGE_DIR}:/home/nvidia/nvidia_sdk