services:
  starrupture:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starrupture-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
    volumes:
      - ./data:/home/steam/data
    entrypoint: ["/home/steam/server/run.sh"]
