name: local
version: 1.0.0
schema: v1
models:
  - name: Gemma4 E4B (97)
    provider: ollama
    model: gemma4:e4b
    roles:
      - chat
      - edit
      - apply
      - summarize
    capabilities:
      - tool_use
    apiBase: http://192.168.242.55:11434
  - name: Gemma4 E2B (55)
    provider: ollama
    model: gemma4:e2b
    roles:
      - autocomplete
    apiBase: http://192.168.242.55:11434